version: '3.8'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile-mod
    ports:
      - "8088:8088"
      - "8087:7979"
      - "2345:2345"
    working_dir: /src/cmd/gateway
    volumes:
      - ./src:/src
      - go-cache:/go-cache
      - ./air-config.toml:/air-config.toml
    environment:
      GOCACHE: /go-cache
    entrypoint: ["air", "-c", "/air-config.toml"]
volumes:
  go-cache: